### ISSUE TITLE
Дублирование интерфейса

### ISSUE THREAD

**Issue by Masynchin** [BobaUbisoft17/chsuBot#6]
https://github.com/BobaUbisoft17/chsuBot/blob/fcf9cca8d0b66321b8c0487c9eed0cfdef5fea6a/internal/reloadSchedule/updateSchedule.go#L19-L24

https://github.com/BobaUbisoft17/chsuBot/blob/fcf9cca8d0b66321b8c0487c9eed0cfdef5fea6a/internal/database/groupDb.go#L15-L19

https://github.com/BobaUbisoft17/chsuBot/blob/fcf9cca8d0b66321b8c0487c9eed0cfdef5fea6a/internal/chsuAPI/struct.go#L5-L10

https://github.com/BobaUbisoft17/chsuBot/blob/fcf9cca8d0b66321b8c0487c9eed0cfdef5fea6a/internal/bot/bot.go#L26-L31

**Comment by BobaUbisoft17** [comment]
А в чём проблема?

**Comment by Masynchin** [comment]
> А в чём проблема?

По сравнению с наличием одного и только одного интерфейса:

- Труднее менять код интерфейса, так как файлов и видов больше одного
- Слабая синхронизация. Изменение одного интерфейса не влияет на другой
- Отсутствие единой точки отказа. Чтобы использовать один и тот же логгер, он должен реализовать четыре разных интерфейса, вместо одного, почему код может сломаться в четырёх разных местах, а не одном

**Comment by BobaUbisoft17** [comment]
Интерфейс один в каждом пакете, он не импортируется, а создаётся прямо в пакете
Код интерфейса полностью зависит от родительской структуры
Интерфейсы не должны зависеть друг от друга.
Логгер не реализует несколько интерфейсов, а сами интерфейсы реализуют методы логгера. К тому же, если интерфейс не удовлетворяет родителю, то компилятор отказывается компилировать приложение

**Comment by BobaUbisoft17** [comment]
Как я понял, вы хотите предложить импортировать просто тип логгера и использовать его методы без интерфейсов
